version: '3.7'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    ports:
      - 5432:5432
    
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

#    networks:
#      - kong-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5



  migrations:
    depends_on:
      - kong-database
    image: kong/kong-gateway:3.3.0.0
    container_name: kongmigrat
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
#      - KONG_PG_DATABASE=kong
      #- KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    command: kong migrations bootstrap 

 


  kong:
 #   depends_on:
 #     - kong-database
    image: kong/kong-gateway:3.3.0.0
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      #- #KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA 
      #- KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl http2
      #- KONG_NGINX_HTTP_RESOLVER=8.8.8.8
      #- KONG_TRUSTED_IPS=0.0.0.0/0,::/0
     # - KONG_REAL_IP_RECURSIVE=on
    ports:
      - 80:8000
      - 8443:8443 
      - 8001:8001 
      - 8444:8444 
      - 8002:8002
      - 8445:8445
      - 8003:8003 
      - 8004:8004 
#      - 127.0.0.1:8001:8001
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://127.0.0.1:8001/status"]
      interval: 5s
      timeout: 2s
      retries: 15
  
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    ports:
      - 1337:1337
##---------------------------
networks: 
  network1:
    name: kong-net
    external: true

#networks:
#  default:
    # Use a custom driver
#    driver: kong-net



#  networks:
#    default:
#      external:true
#        name: test
#  networks:
#    default:
    # Use a custom driver
#    driver: kong-net 

#  networks:
 #   kong-net:
 #     name: kong-net
#        external: true
  #   #  docker run -d -p 1337:1337 --network kong-net --name konga pantsel/konga
